// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRT_Uz23mVlmUQKUpryWSxHEuPm-QEAk',
    appId: '1:647745759998:web:8b75a60c064013676cd3af',
    messagingSenderId: '647745759998',
    projectId: 'tech-hub-master',
    authDomain: 'tech-hub-master.firebaseapp.com',
    storageBucket: 'tech-hub-master.firebasestorage.app',
    measurementId: 'G-0F6HTQRL10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8e7g5gXAOag2lJlMTvSLK3OSaZcGz82E',
    appId: '1:647745759998:android:b38325b6a71916e66cd3af',
    messagingSenderId: '647745759998',
    projectId: 'tech-hub-master',
    storageBucket: 'tech-hub-master.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU6Pab6SIU0x-9M5u6BWgrw2qfudR3HP8',
    appId: '1:647745759998:ios:d418c4dda3e652a46cd3af',
    messagingSenderId: '647745759998',
    projectId: 'tech-hub-master',
    storageBucket: 'tech-hub-master.firebasestorage.app',
    iosBundleId: 'com.example.techHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU6Pab6SIU0x-9M5u6BWgrw2qfudR3HP8',
    appId: '1:647745759998:ios:d418c4dda3e652a46cd3af',
    messagingSenderId: '647745759998',
    projectId: 'tech-hub-master',
    storageBucket: 'tech-hub-master.firebasestorage.app',
    iosBundleId: 'com.example.techHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSRT_Uz23mVlmUQKUpryWSxHEuPm-QEAk',
    appId: '1:647745759998:web:3362c530acb2dc2b6cd3af',
    messagingSenderId: '647745759998',
    projectId: 'tech-hub-master',
    authDomain: 'tech-hub-master.firebaseapp.com',
    storageBucket: 'tech-hub-master.firebasestorage.app',
    measurementId: 'G-5NKFTY9M4Z',
  );
}
